### ISSUE TITLE
SHA.sha1 Error

### ISSUE THREAD

**Issue by zengfengbo** [OpenGene/OpenGene.jl#14]
julia> using OpenGene

julia> using OpenGene.Reference

julia> hg19 = load_assembly("hg19")
INFO: checking SHA1...
ERROR: MethodError: `lowercase` has no method matching lowercase(::Array{UInt8,1})
 in check_sha1 at /Users/fb/.julia/v0.4/OpenGene/src/Reference/Genome/downloader.jl:7
 in download_assembly at /Users/fb/.julia/v0.4/OpenGene/src/Reference/Genome/downloader.jl:51
 in load_assembly at /Users/fb/.julia/v0.4/OpenGene/src/Reference/Genome/reader.jl:11

**Comment by zengfengbo** [comment]
# I solved it adding this.

$ vi /Users/fb/.julia/v0.4/OpenGene/src/Reference/Genome/downloader.jl

 filehash = join(map(i -> @sprintf("%02x", i), filehash), "")

**Comment by sfchen** [comment]
Checking this issue...

**Comment by sfchen** [comment]
This is an issue of latest `SHA` package

**Comment by sfchen** [comment]
Your change works with new `SHA` checkout from github, but fails with `SHA` from METADA.

Did you ever checkout `SHA` ?

**Comment by zengfengbo** [comment]
I readd the `SHA` package, it works.
