### ISSUE TITLE
[JulialangOrgCN] 可以同个能联系到阁下的电子邮件地址么？

### ISSUE THREAD

**Issue by nagexiucai** [OpenGene/OpenGene.jl#19]
感谢接受来自 @JulialangOrgCN 的邀请 :)
没能在GitHub主页上看到阁下的电子邮件地址。
可以转到JulialangOrgCN的GitHub主页获取用于回复的电子邮件地址。

**Comment by sfchen** [comment]
chen@haplox.com
wechat: opengene

**Comment by nagexiucai** [comment]
thanks, i will contact y later :)
