### ISSUE TITLE
install "OpenGeen"

### ISSUE THREAD

**Issue by homeobox155Q4** [OpenGene/OpenGene.jl#23]
Hello,

I'm a beginner, and I'm starting to analyse NGS data (RNA-Ses, Exomes, Chip-Seq,...).
Unfortunately, I can't install Julia's "OpenGene" package in my MacBook Pro.

I would like to know if there is another package or a particular procedure.
I thank you, and congratulate the whole community for the development of Julia.

Kind regards

homeo

**Comment by homeobox155Q4** [comment]
Sorry, i would like say "OpenGene" in the title.

**Comment by sfchen** [comment]
Hi, This project is not being maintained.
