### ISSUE TITLE
Sam/bam IO

### ISSUE THREAD

**Issue by zhmz90** [OpenGene/OpenGene.jl#3]
I will try to implement sam and bam file IO. Maybe need one week or two.

**Comment by sfchen** [comment]
Great!

Create a sambam folder under src/IO/

For bam, suggest to wrap a C library like htslib or bamtools

**Comment by zhmz90** [comment]
That's a good idea. I chose wrapping htslib because I tried before.

**Comment by sfchen** [comment]
That's good, you can take a look at rust-htslib first

https://github.com/rust-bio/rust-htslib

**Comment by sfchen** [comment]
You can also take a look at pysam https://github.com/pysam-developers/pysam

**Comment by zhmz90** [comment]
I am going to  spend  a week or ten days to learn the codes of current wrappers.
